version: '3.9'
networks:
  roboshop:
    driver: bridge
volumes:
  mongodb:
  redis:
  mysql:
Services: 
  mongodb:
  image: mongodb:v1
  container_name: mongodb
  volumes:
  - type: volumes
    source: mongodb
    target: /data/db
    volume: 
      nocopy: true
  
  redis:
    image: redis
    container_name: redis
    volumes:
    - type: volume
      source: redis
      target: /data
      volume: 
         nocopy: true

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  
  web:
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis